#include <TFile.h>
#include <TTree.h>
#include <algorithm>
#include <fstream>
#include <iostream>
#include <sstream>
#include <string>
using namespace std;

int main(int argc,char** argv){
  if(argc!=3){ cerr<<"Usage: "<<argv[0]<<" input.txt output.root\n"; return 1; }
  ifstream in(argv[1]); if(!in){ cerr<<"Cannot open "<<argv[1]<<"\n"; return 2; }
  TFile out(argv[2],"RECREATE");
  TTree tree("PhotonEfficiency","Photon efficiency tag-and-probe hypotheses");
  const int NNEU=5, NANY=3, NGEN=12;
  int runnum;
  int evnum;
  int helicity;
  int is_mc;
  int sample_kind;
  int clasdis_topology;
  int has_mc_particle;
  int has_mc_recmatch;
  int has_mc_lund;
  int gen_n_electron;
  int gen_n_proton;
  int gen_n_photon;
  int gen_n_pi0_photon;
  int gen_n_other;
  double beam_energy;
  double torus;
  double solenoid;
  double mc_weight;
  int rec_rows;
  int n_neutral;
  int n_pid22;
  int n_pid2112;
  int n_pid0_neutral;
  double Q2;
  double W;
  double xB;
  double y;
  double minus_t;
  double e_p;
  double e_theta;
  double e_phi;
  double e_vx;
  double e_vy;
  double e_vz;
  int p_rec_index;
  int p_detector;
  int p_pass_standard;
  double p_raw_p;
  double p_raw_theta;
  double p_raw_phi;
  double p_corr_p;
  double p_corr_theta;
  double p_corr_phi;
  double p_vz;
  int tag_rec_index;
  int tag_detector;
  int tag_status;
  int tag_pass_beta;
  int tag_pass_fiducial;
  double tag_raw_p;
  double tag_raw_theta;
  double tag_raw_phi;
  double tag_beta;
  double tag_corr_p;
  double tag_corr_theta;
  double tag_corr_phi;
  double tag_x;
  double tag_y;
  double tag_z;
  double tag_r;
  double Mx2_ep;
  double Mx_ep;
  double Mx2_epg_raw;
  double probe_raw_E;
  double probe_raw_p;
  double probe_raw_theta;
  double probe_raw_phi;
  double probe_raw_px;
  double probe_raw_py;
  double probe_raw_pz;
  double Mx2_epg_corr;
  double probe_corr_E;
  double probe_corr_p;
  double probe_corr_theta;
  double probe_corr_phi;
  double probe_corr_px;
  double probe_corr_py;
  double probe_corr_pz;
  int truth_probe_index;
  int truth_probe_pid;
  int truth_probe_parent;
  double truth_probe_p;
  double truth_probe_theta;
  double truth_probe_phi;
  double truth_probe_delta_alpha;
  int truth_tag_index;
  int truth_tag_pid;
  int truth_tag_parent;
  double truth_tag_p;
  double truth_tag_theta;
  double truth_tag_phi;
  double truth_tag_delta_alpha;
  int mc_probe_index;
  int mc_probe_pid;
  int mc_probe_parent;
  double mc_probe_p;
  double mc_probe_theta;
  double mc_probe_phi;
  double mc_probe_delta_alpha_pred;
  int mc_probe_rec_index;
  int mc_probe_rec_pid;
  int mc_probe_rec_charge;
  int mc_probe_rec_status;
  int mc_probe_rec_detector;
  double mc_probe_rec_p;
  double mc_probe_rec_theta;
  double mc_probe_rec_phi;
  double mc_probe_rec_delta_alpha_truth;
  int mc_tag_index;
  int mc_tag_pid;
  int mc_tag_parent;
  double mc_tag_p;
  double mc_tag_theta;
  double mc_tag_phi;
  int skim_version;
  Long64_t source_file_hash;
  int gen_n_positron;
  int gen_n_antiproton;
  int gen_n_neutron;
  int gen_n_piplus;
  int gen_n_piminus;
  int gen_n_kplus;
  int gen_n_kminus;
  int gen_n_pi0;
  int mc_e_match_count;
  int mc_e_index;
  int mc_e_pid;
  double mc_e_p;
  double mc_e_theta;
  double mc_e_phi;
  double mc_e_delta_alpha;
  int mc_p_match_count;
  int mc_p_index;
  int mc_p_pid;
  double mc_p_p;
  double mc_p_theta;
  double mc_p_phi;
  double mc_p_delta_alpha;
  int mc_tag_match_count;
  double mc_tag_delta_alpha;
  int mc_probe_n_rec_matches;
  int mc_probe_n_rec_pid22;
  int mc_probe_n_rec_pid11;
  int mc_probe_n_rec_pid2112;
  int mc_probe_n_rec_neutral;
  int mc_probe_n_rec_ft;
  int mc_probe_n_rec_fd;
  int mc_probe_n_rec_pid22_ft;
  int mc_probe_n_rec_pid22_fd;
  int mc_probe_n_rec_pid11_ft;
  int mc_probe_n_rec_pid11_fd;
  double mc_probe_rec_beta;
  double mc_probe_rec_chi2pid;
  double mc_probe_rec_x;
  double mc_probe_rec_y;
  double mc_probe_rec_z;
  double mc_probe_rec_response_energy;
  double mc_probe_rec_pcal_energy;
  double mc_probe_rec_ecin_energy;
  double mc_probe_rec_ecout_energy;
  double mc_probe_rec_ecal_energy;
  double mc_probe_rec_ft_energy;
  double mc_probe_rec_ft_radius;
  double tag_chi2pid;
  double tag_response_energy;
  double tag_pcal_energy;
  double tag_ecin_energy;
  double tag_ecout_energy;
  double tag_ecal_energy;
  int tag_pcal_sector;
  double tag_pcal_lu;
  double tag_pcal_lv;
  double tag_pcal_lw;
  double tag_ft_energy;
  double tag_ft_radius;
  int neutral_idx[5];
  int neutral_pid[5];
  int neutral_charge[5];
  int neutral_status[5];
  int neutral_detector[5];
  double neutral_p[5];
  double neutral_theta[5];
  double neutral_phi[5];
  double neutral_delta_alpha[5];
  double neutral_x[5];
  double neutral_y[5];
  double neutral_z[5];
  double neutral_beta[5];
  double neutral_chi2pid[5];
  double neutral_response_energy[5];
  double neutral_pcal_energy[5];
  double neutral_ecin_energy[5];
  double neutral_ecout_energy[5];
  double neutral_ecal_energy[5];
  int neutral_pcal_sector[5];
  double neutral_pcal_lu[5];
  double neutral_pcal_lv[5];
  double neutral_pcal_lw[5];
  double neutral_ft_energy[5];
  double neutral_ft_radius[5];
  double neutral_corr_p[5];
  double neutral_corr_theta[5];
  double neutral_corr_phi[5];
  int neutral_mc_match_count[5];
  int neutral_mc_index[5];
  int neutral_mc_pid[5];
  double neutral_mc_p[5];
  double neutral_mc_theta[5];
  double neutral_mc_phi[5];
  double neutral_mc_delta_alpha[5];
  int any_idx[3];
  int any_pid[3];
  int any_charge[3];
  int any_status[3];
  int any_detector[3];
  double any_p[3];
  double any_theta[3];
  double any_phi[3];
  double any_delta_alpha[3];
  double any_x[3];
  double any_y[3];
  double any_z[3];
  double any_beta[3];
  double any_chi2pid[3];
  double any_response_energy[3];
  double any_pcal_energy[3];
  double any_ecin_energy[3];
  double any_ecout_energy[3];
  double any_ecal_energy[3];
  int any_pcal_sector[3];
  double any_pcal_lu[3];
  double any_pcal_lv[3];
  double any_pcal_lw[3];
  double any_ft_energy[3];
  double any_ft_radius[3];
  double any_corr_p[3];
  double any_corr_theta[3];
  double any_corr_phi[3];
  int any_mc_match_count[3];
  int any_mc_index[3];
  int any_mc_pid[3];
  double any_mc_p[3];
  double any_mc_theta[3];
  double any_mc_phi[3];
  double any_mc_delta_alpha[3];
  tree.Branch("runnum",&runnum,"runnum/I");
  tree.Branch("evnum",&evnum,"evnum/I");
  tree.Branch("helicity",&helicity,"helicity/I");
  tree.Branch("is_mc",&is_mc,"is_mc/I");
  tree.Branch("sample_kind",&sample_kind,"sample_kind/I");
  tree.Branch("clasdis_topology",&clasdis_topology,"clasdis_topology/I");
  tree.Branch("has_mc_particle",&has_mc_particle,"has_mc_particle/I");
  tree.Branch("has_mc_recmatch",&has_mc_recmatch,"has_mc_recmatch/I");
  tree.Branch("has_mc_lund",&has_mc_lund,"has_mc_lund/I");
  tree.Branch("gen_n_electron",&gen_n_electron,"gen_n_electron/I");
  tree.Branch("gen_n_proton",&gen_n_proton,"gen_n_proton/I");
  tree.Branch("gen_n_photon",&gen_n_photon,"gen_n_photon/I");
  tree.Branch("gen_n_pi0_photon",&gen_n_pi0_photon,"gen_n_pi0_photon/I");
  tree.Branch("gen_n_other",&gen_n_other,"gen_n_other/I");
  tree.Branch("beam_energy",&beam_energy,"beam_energy/D");
  tree.Branch("torus",&torus,"torus/D");
  tree.Branch("solenoid",&solenoid,"solenoid/D");
  tree.Branch("mc_weight",&mc_weight,"mc_weight/D");
  tree.Branch("rec_rows",&rec_rows,"rec_rows/I");
  tree.Branch("n_neutral",&n_neutral,"n_neutral/I");
  tree.Branch("n_pid22",&n_pid22,"n_pid22/I");
  tree.Branch("n_pid2112",&n_pid2112,"n_pid2112/I");
  tree.Branch("n_pid0_neutral",&n_pid0_neutral,"n_pid0_neutral/I");
  tree.Branch("Q2",&Q2,"Q2/D");
  tree.Branch("W",&W,"W/D");
  tree.Branch("xB",&xB,"xB/D");
  tree.Branch("y",&y,"y/D");
  tree.Branch("minus_t",&minus_t,"minus_t/D");
  tree.Branch("e_p",&e_p,"e_p/D");
  tree.Branch("e_theta",&e_theta,"e_theta/D");
  tree.Branch("e_phi",&e_phi,"e_phi/D");
  tree.Branch("e_vx",&e_vx,"e_vx/D");
  tree.Branch("e_vy",&e_vy,"e_vy/D");
  tree.Branch("e_vz",&e_vz,"e_vz/D");
  tree.Branch("p_rec_index",&p_rec_index,"p_rec_index/I");
  tree.Branch("p_detector",&p_detector,"p_detector/I");
  tree.Branch("p_pass_standard",&p_pass_standard,"p_pass_standard/I");
  tree.Branch("p_raw_p",&p_raw_p,"p_raw_p/D");
  tree.Branch("p_raw_theta",&p_raw_theta,"p_raw_theta/D");
  tree.Branch("p_raw_phi",&p_raw_phi,"p_raw_phi/D");
  tree.Branch("p_corr_p",&p_corr_p,"p_corr_p/D");
  tree.Branch("p_corr_theta",&p_corr_theta,"p_corr_theta/D");
  tree.Branch("p_corr_phi",&p_corr_phi,"p_corr_phi/D");
  tree.Branch("p_vz",&p_vz,"p_vz/D");
  tree.Branch("tag_rec_index",&tag_rec_index,"tag_rec_index/I");
  tree.Branch("tag_detector",&tag_detector,"tag_detector/I");
  tree.Branch("tag_status",&tag_status,"tag_status/I");
  tree.Branch("tag_pass_beta",&tag_pass_beta,"tag_pass_beta/I");
  tree.Branch("tag_pass_fiducial",&tag_pass_fiducial,"tag_pass_fiducial/I");
  tree.Branch("tag_raw_p",&tag_raw_p,"tag_raw_p/D");
  tree.Branch("tag_raw_theta",&tag_raw_theta,"tag_raw_theta/D");
  tree.Branch("tag_raw_phi",&tag_raw_phi,"tag_raw_phi/D");
  tree.Branch("tag_beta",&tag_beta,"tag_beta/D");
  tree.Branch("tag_corr_p",&tag_corr_p,"tag_corr_p/D");
  tree.Branch("tag_corr_theta",&tag_corr_theta,"tag_corr_theta/D");
  tree.Branch("tag_corr_phi",&tag_corr_phi,"tag_corr_phi/D");
  tree.Branch("tag_x",&tag_x,"tag_x/D");
  tree.Branch("tag_y",&tag_y,"tag_y/D");
  tree.Branch("tag_z",&tag_z,"tag_z/D");
  tree.Branch("tag_r",&tag_r,"tag_r/D");
  tree.Branch("Mx2_ep",&Mx2_ep,"Mx2_ep/D");
  tree.Branch("Mx_ep",&Mx_ep,"Mx_ep/D");
  tree.Branch("Mx2_epg_raw",&Mx2_epg_raw,"Mx2_epg_raw/D");
  tree.Branch("probe_raw_E",&probe_raw_E,"probe_raw_E/D");
  tree.Branch("probe_raw_p",&probe_raw_p,"probe_raw_p/D");
  tree.Branch("probe_raw_theta",&probe_raw_theta,"probe_raw_theta/D");
  tree.Branch("probe_raw_phi",&probe_raw_phi,"probe_raw_phi/D");
  tree.Branch("probe_raw_px",&probe_raw_px,"probe_raw_px/D");
  tree.Branch("probe_raw_py",&probe_raw_py,"probe_raw_py/D");
  tree.Branch("probe_raw_pz",&probe_raw_pz,"probe_raw_pz/D");
  tree.Branch("Mx2_epg_corr",&Mx2_epg_corr,"Mx2_epg_corr/D");
  tree.Branch("probe_corr_E",&probe_corr_E,"probe_corr_E/D");
  tree.Branch("probe_corr_p",&probe_corr_p,"probe_corr_p/D");
  tree.Branch("probe_corr_theta",&probe_corr_theta,"probe_corr_theta/D");
  tree.Branch("probe_corr_phi",&probe_corr_phi,"probe_corr_phi/D");
  tree.Branch("probe_corr_px",&probe_corr_px,"probe_corr_px/D");
  tree.Branch("probe_corr_py",&probe_corr_py,"probe_corr_py/D");
  tree.Branch("probe_corr_pz",&probe_corr_pz,"probe_corr_pz/D");
  tree.Branch("truth_probe_index",&truth_probe_index,"truth_probe_index/I");
  tree.Branch("truth_probe_pid",&truth_probe_pid,"truth_probe_pid/I");
  tree.Branch("truth_probe_parent",&truth_probe_parent,"truth_probe_parent/I");
  tree.Branch("truth_probe_p",&truth_probe_p,"truth_probe_p/D");
  tree.Branch("truth_probe_theta",&truth_probe_theta,"truth_probe_theta/D");
  tree.Branch("truth_probe_phi",&truth_probe_phi,"truth_probe_phi/D");
  tree.Branch("truth_probe_delta_alpha",&truth_probe_delta_alpha,"truth_probe_delta_alpha/D");
  tree.Branch("truth_tag_index",&truth_tag_index,"truth_tag_index/I");
  tree.Branch("truth_tag_pid",&truth_tag_pid,"truth_tag_pid/I");
  tree.Branch("truth_tag_parent",&truth_tag_parent,"truth_tag_parent/I");
  tree.Branch("truth_tag_p",&truth_tag_p,"truth_tag_p/D");
  tree.Branch("truth_tag_theta",&truth_tag_theta,"truth_tag_theta/D");
  tree.Branch("truth_tag_phi",&truth_tag_phi,"truth_tag_phi/D");
  tree.Branch("truth_tag_delta_alpha",&truth_tag_delta_alpha,"truth_tag_delta_alpha/D");
  tree.Branch("mc_probe_index",&mc_probe_index,"mc_probe_index/I");
  tree.Branch("mc_probe_pid",&mc_probe_pid,"mc_probe_pid/I");
  tree.Branch("mc_probe_parent",&mc_probe_parent,"mc_probe_parent/I");
  tree.Branch("mc_probe_p",&mc_probe_p,"mc_probe_p/D");
  tree.Branch("mc_probe_theta",&mc_probe_theta,"mc_probe_theta/D");
  tree.Branch("mc_probe_phi",&mc_probe_phi,"mc_probe_phi/D");
  tree.Branch("mc_probe_delta_alpha_pred",&mc_probe_delta_alpha_pred,"mc_probe_delta_alpha_pred/D");
  tree.Branch("mc_probe_rec_index",&mc_probe_rec_index,"mc_probe_rec_index/I");
  tree.Branch("mc_probe_rec_pid",&mc_probe_rec_pid,"mc_probe_rec_pid/I");
  tree.Branch("mc_probe_rec_charge",&mc_probe_rec_charge,"mc_probe_rec_charge/I");
  tree.Branch("mc_probe_rec_status",&mc_probe_rec_status,"mc_probe_rec_status/I");
  tree.Branch("mc_probe_rec_detector",&mc_probe_rec_detector,"mc_probe_rec_detector/I");
  tree.Branch("mc_probe_rec_p",&mc_probe_rec_p,"mc_probe_rec_p/D");
  tree.Branch("mc_probe_rec_theta",&mc_probe_rec_theta,"mc_probe_rec_theta/D");
  tree.Branch("mc_probe_rec_phi",&mc_probe_rec_phi,"mc_probe_rec_phi/D");
  tree.Branch("mc_probe_rec_delta_alpha_truth",&mc_probe_rec_delta_alpha_truth,"mc_probe_rec_delta_alpha_truth/D");
  tree.Branch("mc_tag_index",&mc_tag_index,"mc_tag_index/I");
  tree.Branch("mc_tag_pid",&mc_tag_pid,"mc_tag_pid/I");
  tree.Branch("mc_tag_parent",&mc_tag_parent,"mc_tag_parent/I");
  tree.Branch("mc_tag_p",&mc_tag_p,"mc_tag_p/D");
  tree.Branch("mc_tag_theta",&mc_tag_theta,"mc_tag_theta/D");
  tree.Branch("mc_tag_phi",&mc_tag_phi,"mc_tag_phi/D");
  tree.Branch("skim_version",&skim_version,"skim_version/I");
  tree.Branch("source_file_hash",&source_file_hash,"source_file_hash/L");
  tree.Branch("gen_n_positron",&gen_n_positron,"gen_n_positron/I");
  tree.Branch("gen_n_antiproton",&gen_n_antiproton,"gen_n_antiproton/I");
  tree.Branch("gen_n_neutron",&gen_n_neutron,"gen_n_neutron/I");
  tree.Branch("gen_n_piplus",&gen_n_piplus,"gen_n_piplus/I");
  tree.Branch("gen_n_piminus",&gen_n_piminus,"gen_n_piminus/I");
  tree.Branch("gen_n_kplus",&gen_n_kplus,"gen_n_kplus/I");
  tree.Branch("gen_n_kminus",&gen_n_kminus,"gen_n_kminus/I");
  tree.Branch("gen_n_pi0",&gen_n_pi0,"gen_n_pi0/I");
  tree.Branch("mc_e_match_count",&mc_e_match_count,"mc_e_match_count/I");
  tree.Branch("mc_e_index",&mc_e_index,"mc_e_index/I");
  tree.Branch("mc_e_pid",&mc_e_pid,"mc_e_pid/I");
  tree.Branch("mc_e_p",&mc_e_p,"mc_e_p/D");
  tree.Branch("mc_e_theta",&mc_e_theta,"mc_e_theta/D");
  tree.Branch("mc_e_phi",&mc_e_phi,"mc_e_phi/D");
  tree.Branch("mc_e_delta_alpha",&mc_e_delta_alpha,"mc_e_delta_alpha/D");
  tree.Branch("mc_p_match_count",&mc_p_match_count,"mc_p_match_count/I");
  tree.Branch("mc_p_index",&mc_p_index,"mc_p_index/I");
  tree.Branch("mc_p_pid",&mc_p_pid,"mc_p_pid/I");
  tree.Branch("mc_p_p",&mc_p_p,"mc_p_p/D");
  tree.Branch("mc_p_theta",&mc_p_theta,"mc_p_theta/D");
  tree.Branch("mc_p_phi",&mc_p_phi,"mc_p_phi/D");
  tree.Branch("mc_p_delta_alpha",&mc_p_delta_alpha,"mc_p_delta_alpha/D");
  tree.Branch("mc_tag_match_count",&mc_tag_match_count,"mc_tag_match_count/I");
  tree.Branch("mc_tag_delta_alpha",&mc_tag_delta_alpha,"mc_tag_delta_alpha/D");
  tree.Branch("mc_probe_n_rec_matches",&mc_probe_n_rec_matches,"mc_probe_n_rec_matches/I");
  tree.Branch("mc_probe_n_rec_pid22",&mc_probe_n_rec_pid22,"mc_probe_n_rec_pid22/I");
  tree.Branch("mc_probe_n_rec_pid11",&mc_probe_n_rec_pid11,"mc_probe_n_rec_pid11/I");
  tree.Branch("mc_probe_n_rec_pid2112",&mc_probe_n_rec_pid2112,"mc_probe_n_rec_pid2112/I");
  tree.Branch("mc_probe_n_rec_neutral",&mc_probe_n_rec_neutral,"mc_probe_n_rec_neutral/I");
  tree.Branch("mc_probe_n_rec_ft",&mc_probe_n_rec_ft,"mc_probe_n_rec_ft/I");
  tree.Branch("mc_probe_n_rec_fd",&mc_probe_n_rec_fd,"mc_probe_n_rec_fd/I");
  tree.Branch("mc_probe_n_rec_pid22_ft",&mc_probe_n_rec_pid22_ft,"mc_probe_n_rec_pid22_ft/I");
  tree.Branch("mc_probe_n_rec_pid22_fd",&mc_probe_n_rec_pid22_fd,"mc_probe_n_rec_pid22_fd/I");
  tree.Branch("mc_probe_n_rec_pid11_ft",&mc_probe_n_rec_pid11_ft,"mc_probe_n_rec_pid11_ft/I");
  tree.Branch("mc_probe_n_rec_pid11_fd",&mc_probe_n_rec_pid11_fd,"mc_probe_n_rec_pid11_fd/I");
  tree.Branch("mc_probe_rec_beta",&mc_probe_rec_beta,"mc_probe_rec_beta/D");
  tree.Branch("mc_probe_rec_chi2pid",&mc_probe_rec_chi2pid,"mc_probe_rec_chi2pid/D");
  tree.Branch("mc_probe_rec_x",&mc_probe_rec_x,"mc_probe_rec_x/D");
  tree.Branch("mc_probe_rec_y",&mc_probe_rec_y,"mc_probe_rec_y/D");
  tree.Branch("mc_probe_rec_z",&mc_probe_rec_z,"mc_probe_rec_z/D");
  tree.Branch("mc_probe_rec_response_energy",&mc_probe_rec_response_energy,"mc_probe_rec_response_energy/D");
  tree.Branch("mc_probe_rec_pcal_energy",&mc_probe_rec_pcal_energy,"mc_probe_rec_pcal_energy/D");
  tree.Branch("mc_probe_rec_ecin_energy",&mc_probe_rec_ecin_energy,"mc_probe_rec_ecin_energy/D");
  tree.Branch("mc_probe_rec_ecout_energy",&mc_probe_rec_ecout_energy,"mc_probe_rec_ecout_energy/D");
  tree.Branch("mc_probe_rec_ecal_energy",&mc_probe_rec_ecal_energy,"mc_probe_rec_ecal_energy/D");
  tree.Branch("mc_probe_rec_ft_energy",&mc_probe_rec_ft_energy,"mc_probe_rec_ft_energy/D");
  tree.Branch("mc_probe_rec_ft_radius",&mc_probe_rec_ft_radius,"mc_probe_rec_ft_radius/D");
  tree.Branch("tag_chi2pid",&tag_chi2pid,"tag_chi2pid/D");
  tree.Branch("tag_response_energy",&tag_response_energy,"tag_response_energy/D");
  tree.Branch("tag_pcal_energy",&tag_pcal_energy,"tag_pcal_energy/D");
  tree.Branch("tag_ecin_energy",&tag_ecin_energy,"tag_ecin_energy/D");
  tree.Branch("tag_ecout_energy",&tag_ecout_energy,"tag_ecout_energy/D");
  tree.Branch("tag_ecal_energy",&tag_ecal_energy,"tag_ecal_energy/D");
  tree.Branch("tag_pcal_sector",&tag_pcal_sector,"tag_pcal_sector/I");
  tree.Branch("tag_pcal_lu",&tag_pcal_lu,"tag_pcal_lu/D");
  tree.Branch("tag_pcal_lv",&tag_pcal_lv,"tag_pcal_lv/D");
  tree.Branch("tag_pcal_lw",&tag_pcal_lw,"tag_pcal_lw/D");
  tree.Branch("tag_ft_energy",&tag_ft_energy,"tag_ft_energy/D");
  tree.Branch("tag_ft_radius",&tag_ft_radius,"tag_ft_radius/D");
  tree.Branch("neutral_idx",neutral_idx,"neutral_idx[5]/I");
  tree.Branch("neutral_pid",neutral_pid,"neutral_pid[5]/I");
  tree.Branch("neutral_charge",neutral_charge,"neutral_charge[5]/I");
  tree.Branch("neutral_status",neutral_status,"neutral_status[5]/I");
  tree.Branch("neutral_detector",neutral_detector,"neutral_detector[5]/I");
  tree.Branch("neutral_p",neutral_p,"neutral_p[5]/D");
  tree.Branch("neutral_theta",neutral_theta,"neutral_theta[5]/D");
  tree.Branch("neutral_phi",neutral_phi,"neutral_phi[5]/D");
  tree.Branch("neutral_delta_alpha",neutral_delta_alpha,"neutral_delta_alpha[5]/D");
  tree.Branch("neutral_x",neutral_x,"neutral_x[5]/D");
  tree.Branch("neutral_y",neutral_y,"neutral_y[5]/D");
  tree.Branch("neutral_z",neutral_z,"neutral_z[5]/D");
  tree.Branch("neutral_beta",neutral_beta,"neutral_beta[5]/D");
  tree.Branch("neutral_chi2pid",neutral_chi2pid,"neutral_chi2pid[5]/D");
  tree.Branch("neutral_response_energy",neutral_response_energy,"neutral_response_energy[5]/D");
  tree.Branch("neutral_pcal_energy",neutral_pcal_energy,"neutral_pcal_energy[5]/D");
  tree.Branch("neutral_ecin_energy",neutral_ecin_energy,"neutral_ecin_energy[5]/D");
  tree.Branch("neutral_ecout_energy",neutral_ecout_energy,"neutral_ecout_energy[5]/D");
  tree.Branch("neutral_ecal_energy",neutral_ecal_energy,"neutral_ecal_energy[5]/D");
  tree.Branch("neutral_pcal_sector",neutral_pcal_sector,"neutral_pcal_sector[5]/I");
  tree.Branch("neutral_pcal_lu",neutral_pcal_lu,"neutral_pcal_lu[5]/D");
  tree.Branch("neutral_pcal_lv",neutral_pcal_lv,"neutral_pcal_lv[5]/D");
  tree.Branch("neutral_pcal_lw",neutral_pcal_lw,"neutral_pcal_lw[5]/D");
  tree.Branch("neutral_ft_energy",neutral_ft_energy,"neutral_ft_energy[5]/D");
  tree.Branch("neutral_ft_radius",neutral_ft_radius,"neutral_ft_radius[5]/D");
  tree.Branch("neutral_corr_p",neutral_corr_p,"neutral_corr_p[5]/D");
  tree.Branch("neutral_corr_theta",neutral_corr_theta,"neutral_corr_theta[5]/D");
  tree.Branch("neutral_corr_phi",neutral_corr_phi,"neutral_corr_phi[5]/D");
  tree.Branch("neutral_mc_match_count",neutral_mc_match_count,"neutral_mc_match_count[5]/I");
  tree.Branch("neutral_mc_index",neutral_mc_index,"neutral_mc_index[5]/I");
  tree.Branch("neutral_mc_pid",neutral_mc_pid,"neutral_mc_pid[5]/I");
  tree.Branch("neutral_mc_p",neutral_mc_p,"neutral_mc_p[5]/D");
  tree.Branch("neutral_mc_theta",neutral_mc_theta,"neutral_mc_theta[5]/D");
  tree.Branch("neutral_mc_phi",neutral_mc_phi,"neutral_mc_phi[5]/D");
  tree.Branch("neutral_mc_delta_alpha",neutral_mc_delta_alpha,"neutral_mc_delta_alpha[5]/D");
  tree.Branch("any_idx",any_idx,"any_idx[3]/I");
  tree.Branch("any_pid",any_pid,"any_pid[3]/I");
  tree.Branch("any_charge",any_charge,"any_charge[3]/I");
  tree.Branch("any_status",any_status,"any_status[3]/I");
  tree.Branch("any_detector",any_detector,"any_detector[3]/I");
  tree.Branch("any_p",any_p,"any_p[3]/D");
  tree.Branch("any_theta",any_theta,"any_theta[3]/D");
  tree.Branch("any_phi",any_phi,"any_phi[3]/D");
  tree.Branch("any_delta_alpha",any_delta_alpha,"any_delta_alpha[3]/D");
  tree.Branch("any_x",any_x,"any_x[3]/D");
  tree.Branch("any_y",any_y,"any_y[3]/D");
  tree.Branch("any_z",any_z,"any_z[3]/D");
  tree.Branch("any_beta",any_beta,"any_beta[3]/D");
  tree.Branch("any_chi2pid",any_chi2pid,"any_chi2pid[3]/D");
  tree.Branch("any_response_energy",any_response_energy,"any_response_energy[3]/D");
  tree.Branch("any_pcal_energy",any_pcal_energy,"any_pcal_energy[3]/D");
  tree.Branch("any_ecin_energy",any_ecin_energy,"any_ecin_energy[3]/D");
  tree.Branch("any_ecout_energy",any_ecout_energy,"any_ecout_energy[3]/D");
  tree.Branch("any_ecal_energy",any_ecal_energy,"any_ecal_energy[3]/D");
  tree.Branch("any_pcal_sector",any_pcal_sector,"any_pcal_sector[3]/I");
  tree.Branch("any_pcal_lu",any_pcal_lu,"any_pcal_lu[3]/D");
  tree.Branch("any_pcal_lv",any_pcal_lv,"any_pcal_lv[3]/D");
  tree.Branch("any_pcal_lw",any_pcal_lw,"any_pcal_lw[3]/D");
  tree.Branch("any_ft_energy",any_ft_energy,"any_ft_energy[3]/D");
  tree.Branch("any_ft_radius",any_ft_radius,"any_ft_radius[3]/D");
  tree.Branch("any_corr_p",any_corr_p,"any_corr_p[3]/D");
  tree.Branch("any_corr_theta",any_corr_theta,"any_corr_theta[3]/D");
  tree.Branch("any_corr_phi",any_corr_phi,"any_corr_phi[3]/D");
  tree.Branch("any_mc_match_count",any_mc_match_count,"any_mc_match_count[3]/I");
  tree.Branch("any_mc_index",any_mc_index,"any_mc_index[3]/I");
  tree.Branch("any_mc_pid",any_mc_pid,"any_mc_pid[3]/I");
  tree.Branch("any_mc_p",any_mc_p,"any_mc_p[3]/D");
  tree.Branch("any_mc_theta",any_mc_theta,"any_mc_theta[3]/D");
  tree.Branch("any_mc_phi",any_mc_phi,"any_mc_phi[3]/D");
  tree.Branch("any_mc_delta_alpha",any_mc_delta_alpha,"any_mc_delta_alpha[3]/D");
  string line; long long n=0,bad=0;
  while(getline(in,line)){
    if(line.empty() || line[0]=='#') continue;
    istringstream ss(line);
    bool ok=true;
#define RD(x) do{ if(!(ss>>(x))) ok=false; }while(0)
    RD(runnum);
    RD(evnum);
    RD(helicity);
    RD(is_mc);
    RD(sample_kind);
    RD(clasdis_topology);
    RD(has_mc_particle);
    RD(has_mc_recmatch);
    RD(has_mc_lund);
    RD(gen_n_electron);
    RD(gen_n_proton);
    RD(gen_n_photon);
    RD(gen_n_pi0_photon);
    RD(gen_n_other);
    RD(beam_energy);
    RD(torus);
    RD(solenoid);
    RD(mc_weight);
    RD(rec_rows);
    RD(n_neutral);
    RD(n_pid22);
    RD(n_pid2112);
    RD(n_pid0_neutral);
    RD(Q2);
    RD(W);
    RD(xB);
    RD(y);
    RD(minus_t);
    RD(e_p);
    RD(e_theta);
    RD(e_phi);
    RD(e_vx);
    RD(e_vy);
    RD(e_vz);
    RD(p_rec_index);
    RD(p_detector);
    RD(p_pass_standard);
    RD(p_raw_p);
    RD(p_raw_theta);
    RD(p_raw_phi);
    RD(p_corr_p);
    RD(p_corr_theta);
    RD(p_corr_phi);
    RD(p_vz);
    RD(tag_rec_index);
    RD(tag_detector);
    RD(tag_status);
    RD(tag_pass_beta);
    RD(tag_pass_fiducial);
    RD(tag_raw_p);
    RD(tag_raw_theta);
    RD(tag_raw_phi);
    RD(tag_beta);
    RD(tag_corr_p);
    RD(tag_corr_theta);
    RD(tag_corr_phi);
    RD(tag_x);
    RD(tag_y);
    RD(tag_z);
    RD(tag_r);
    RD(Mx2_ep);
    RD(Mx_ep);
    RD(Mx2_epg_raw);
    RD(probe_raw_E);
    RD(probe_raw_p);
    RD(probe_raw_theta);
    RD(probe_raw_phi);
    RD(probe_raw_px);
    RD(probe_raw_py);
    RD(probe_raw_pz);
    RD(Mx2_epg_corr);
    RD(probe_corr_E);
    RD(probe_corr_p);
    RD(probe_corr_theta);
    RD(probe_corr_phi);
    RD(probe_corr_px);
    RD(probe_corr_py);
    RD(probe_corr_pz);
    for(int k=0;k<NNEU;k++){
      RD(neutral_idx[k]);
      RD(neutral_pid[k]);
      RD(neutral_charge[k]);
      RD(neutral_status[k]);
      RD(neutral_detector[k]);
      RD(neutral_p[k]);
      RD(neutral_theta[k]);
      RD(neutral_phi[k]);
      RD(neutral_delta_alpha[k]);
      RD(neutral_x[k]);
      RD(neutral_y[k]);
      RD(neutral_z[k]);
    }
    for(int k=0;k<NANY;k++){
      RD(any_idx[k]);
      RD(any_pid[k]);
      RD(any_charge[k]);
      RD(any_status[k]);
      RD(any_detector[k]);
      RD(any_p[k]);
      RD(any_theta[k]);
      RD(any_phi[k]);
      RD(any_delta_alpha[k]);
      RD(any_x[k]);
      RD(any_y[k]);
      RD(any_z[k]);
    }
    RD(truth_probe_index);
    RD(truth_probe_pid);
    RD(truth_probe_parent);
    RD(truth_probe_p);
    RD(truth_probe_theta);
    RD(truth_probe_phi);
    RD(truth_probe_delta_alpha);
    RD(truth_tag_index);
    RD(truth_tag_pid);
    RD(truth_tag_parent);
    RD(truth_tag_p);
    RD(truth_tag_theta);
    RD(truth_tag_phi);
    RD(truth_tag_delta_alpha);
    RD(mc_probe_index);
    RD(mc_probe_pid);
    RD(mc_probe_parent);
    RD(mc_probe_p);
    RD(mc_probe_theta);
    RD(mc_probe_phi);
    RD(mc_probe_delta_alpha_pred);
    RD(mc_probe_rec_index);
    RD(mc_probe_rec_pid);
    RD(mc_probe_rec_charge);
    RD(mc_probe_rec_status);
    RD(mc_probe_rec_detector);
    RD(mc_probe_rec_p);
    RD(mc_probe_rec_theta);
    RD(mc_probe_rec_phi);
    RD(mc_probe_rec_delta_alpha_truth);
    RD(mc_tag_index);
    RD(mc_tag_pid);
    RD(mc_tag_parent);
    RD(mc_tag_p);
    RD(mc_tag_theta);
    RD(mc_tag_phi);
    RD(skim_version);
    RD(source_file_hash);
    RD(gen_n_positron);
    RD(gen_n_antiproton);
    RD(gen_n_neutron);
    RD(gen_n_piplus);
    RD(gen_n_piminus);
    RD(gen_n_kplus);
    RD(gen_n_kminus);
    RD(gen_n_pi0);
    RD(mc_e_match_count);
    RD(mc_e_index);
    RD(mc_e_pid);
    RD(mc_e_p);
    RD(mc_e_theta);
    RD(mc_e_phi);
    RD(mc_e_delta_alpha);
    RD(mc_p_match_count);
    RD(mc_p_index);
    RD(mc_p_pid);
    RD(mc_p_p);
    RD(mc_p_theta);
    RD(mc_p_phi);
    RD(mc_p_delta_alpha);
    RD(mc_tag_match_count);
    RD(mc_tag_delta_alpha);
    RD(mc_probe_n_rec_matches);
    RD(mc_probe_n_rec_pid22);
    RD(mc_probe_n_rec_pid11);
    RD(mc_probe_n_rec_pid2112);
    RD(mc_probe_n_rec_neutral);
    RD(mc_probe_n_rec_ft);
    RD(mc_probe_n_rec_fd);
    RD(mc_probe_n_rec_pid22_ft);
    RD(mc_probe_n_rec_pid22_fd);
    RD(mc_probe_n_rec_pid11_ft);
    RD(mc_probe_n_rec_pid11_fd);
    RD(mc_probe_rec_beta);
    RD(mc_probe_rec_chi2pid);
    RD(mc_probe_rec_x);
    RD(mc_probe_rec_y);
    RD(mc_probe_rec_z);
    RD(mc_probe_rec_response_energy);
    RD(mc_probe_rec_pcal_energy);
    RD(mc_probe_rec_ecin_energy);
    RD(mc_probe_rec_ecout_energy);
    RD(mc_probe_rec_ecal_energy);
    RD(mc_probe_rec_ft_energy);
    RD(mc_probe_rec_ft_radius);
    RD(tag_chi2pid);
    RD(tag_response_energy);
    RD(tag_pcal_energy);
    RD(tag_ecin_energy);
    RD(tag_ecout_energy);
    RD(tag_ecal_energy);
    RD(tag_pcal_sector);
    RD(tag_pcal_lu);
    RD(tag_pcal_lv);
    RD(tag_pcal_lw);
    RD(tag_ft_energy);
    RD(tag_ft_radius);
    for(int k=0;k<NNEU;k++){
      RD(neutral_beta[k]);
      RD(neutral_chi2pid[k]);
      RD(neutral_response_energy[k]);
      RD(neutral_pcal_energy[k]);
      RD(neutral_ecin_energy[k]);
      RD(neutral_ecout_energy[k]);
      RD(neutral_ecal_energy[k]);
      RD(neutral_pcal_sector[k]);
      RD(neutral_pcal_lu[k]);
      RD(neutral_pcal_lv[k]);
      RD(neutral_pcal_lw[k]);
      RD(neutral_ft_energy[k]);
      RD(neutral_ft_radius[k]);
      RD(neutral_corr_p[k]);
      RD(neutral_corr_theta[k]);
      RD(neutral_corr_phi[k]);
      RD(neutral_mc_match_count[k]);
      RD(neutral_mc_index[k]);
      RD(neutral_mc_pid[k]);
      RD(neutral_mc_p[k]);
      RD(neutral_mc_theta[k]);
      RD(neutral_mc_phi[k]);
      RD(neutral_mc_delta_alpha[k]);
    }
    for(int k=0;k<NANY;k++){
      RD(any_beta[k]);
      RD(any_chi2pid[k]);
      RD(any_response_energy[k]);
      RD(any_pcal_energy[k]);
      RD(any_ecin_energy[k]);
      RD(any_ecout_energy[k]);
      RD(any_ecal_energy[k]);
      RD(any_pcal_sector[k]);
      RD(any_pcal_lu[k]);
      RD(any_pcal_lv[k]);
      RD(any_pcal_lw[k]);
      RD(any_ft_energy[k]);
      RD(any_ft_radius[k]);
      RD(any_corr_p[k]);
      RD(any_corr_theta[k]);
      RD(any_corr_phi[k]);
      RD(any_mc_match_count[k]);
      RD(any_mc_index[k]);
      RD(any_mc_pid[k]);
      RD(any_mc_p[k]);
      RD(any_mc_theta[k]);
      RD(any_mc_phi[k]);
      RD(any_mc_delta_alpha[k]);
    }
#undef RD
    if(!ok){ bad++; continue; }
    tree.Fill(); n++;
  }
  tree.Write();

  string eventPath=string(argv[1])+".events";
  ifstream ein(eventPath);
  long long en=0, ebad=0;
  if(ein){
    TTree etree("PhotonEfficiencyEvents","One accepted-electron event per entry; generated-photon truth closure");
    int ev_skim_version;
    Long64_t ev_source_file_hash;
    int ev_runnum;
    int ev_evnum;
    int ev_helicity;
    int ev_is_mc;
    int ev_sample_kind;
    int ev_clasdis_topology;
    int ev_has_mc_particle;
    int ev_has_mc_recmatch;
    int ev_has_mc_lund;
    int ev_gen_n_electron;
    int ev_gen_n_positron;
    int ev_gen_n_proton;
    int ev_gen_n_antiproton;
    int ev_gen_n_neutron;
    int ev_gen_n_photon;
    int ev_gen_n_pi0_photon;
    int ev_gen_n_piplus;
    int ev_gen_n_piminus;
    int ev_gen_n_kplus;
    int ev_gen_n_kminus;
    int ev_gen_n_pi0;
    int ev_gen_n_other;
    double ev_beam_energy;
    double ev_torus;
    double ev_solenoid;
    double ev_mc_weight;
    double ev_Q2;
    double ev_W;
    double ev_xB;
    double ev_y;
    double ev_e_p;
    double ev_e_theta;
    double ev_e_phi;
    double ev_e_vx;
    double ev_e_vy;
    double ev_e_vz;
    int ev_rec_rows;
    int ev_n_neutral;
    int ev_n_pid22;
    int ev_n_pid2112;
    int ev_n_pid0_neutral;
    int ev_mc_e_match_count;
    int ev_mc_e_index;
    int ev_mc_e_pid;
    double ev_mc_e_p;
    double ev_mc_e_theta;
    double ev_mc_e_phi;
    double ev_mc_e_delta_alpha;
    int ev_rec_pid22_total;
    int ev_rec_pid22_unmatched;
    int ev_rec_pid22_multi_mc;
    int ev_rec_pid22_from_mc22;
    int ev_rec_pid22_from_mc11;
    int ev_rec_pid22_from_other;
    int ev_ft_pid22_total;
    int ev_ft_pid22_from_mc22;
    int ev_ft_pid22_from_mc11;
    int ev_ft_pid22_unmatched;
    int ev_fd_pid22_total;
    int ev_fd_pid22_from_mc22;
    int ev_fd_pid22_from_mc11;
    int ev_fd_pid22_unmatched;
    int ev_ft_pid11_total;
    int ev_ft_pid11_from_mc22;
    int ev_fd_pid11_total;
    int ev_fd_pid11_from_mc22;
    int ev_fd_pid2112_total;
    int ev_fd_pid2112_from_mc22;
    int ev_gen_gamma_total;
    int ev_gen_gamma_overflow;
    int gen_gamma_index[NGEN];
    double gen_gamma_p[NGEN];
    double gen_gamma_theta[NGEN];
    double gen_gamma_phi[NGEN];
    double gen_gamma_vx[NGEN];
    double gen_gamma_vy[NGEN];
    double gen_gamma_vz[NGEN];
    int gen_gamma_n_rec_matches[NGEN];
    int gen_gamma_n_rec_pid22[NGEN];
    int gen_gamma_n_rec_pid11[NGEN];
    int gen_gamma_n_rec_pid2112[NGEN];
    int gen_gamma_n_rec_neutral[NGEN];
    int gen_gamma_n_rec_ft[NGEN];
    int gen_gamma_n_rec_fd[NGEN];
    int gen_gamma_n_rec_pid22_ft[NGEN];
    int gen_gamma_n_rec_pid22_fd[NGEN];
    int gen_gamma_n_rec_pid11_ft[NGEN];
    int gen_gamma_n_rec_pid11_fd[NGEN];
    int gen_gamma_best_rec_index[NGEN];
    int gen_gamma_best_rec_pid[NGEN];
    int gen_gamma_best_rec_charge[NGEN];
    int gen_gamma_best_rec_status[NGEN];
    int gen_gamma_best_rec_detector[NGEN];
    double gen_gamma_best_rec_p[NGEN];
    double gen_gamma_best_rec_theta[NGEN];
    double gen_gamma_best_rec_phi[NGEN];
    double gen_gamma_best_rec_delta_alpha[NGEN];
    double gen_gamma_best_rec_beta[NGEN];
    double gen_gamma_best_rec_chi2pid[NGEN];
    double gen_gamma_best_rec_x[NGEN];
    double gen_gamma_best_rec_y[NGEN];
    double gen_gamma_best_rec_z[NGEN];
    double gen_gamma_best_rec_response_energy[NGEN];
    double gen_gamma_best_rec_pcal_energy[NGEN];
    double gen_gamma_best_rec_ecin_energy[NGEN];
    double gen_gamma_best_rec_ecout_energy[NGEN];
    double gen_gamma_best_rec_ecal_energy[NGEN];
    double gen_gamma_best_rec_ft_energy[NGEN];
    double gen_gamma_best_rec_ft_radius[NGEN];
    etree.Branch("skim_version",&ev_skim_version,"skim_version/I");
    etree.Branch("source_file_hash",&ev_source_file_hash,"source_file_hash/L");
    etree.Branch("runnum",&ev_runnum,"runnum/I");
    etree.Branch("evnum",&ev_evnum,"evnum/I");
    etree.Branch("helicity",&ev_helicity,"helicity/I");
    etree.Branch("is_mc",&ev_is_mc,"is_mc/I");
    etree.Branch("sample_kind",&ev_sample_kind,"sample_kind/I");
    etree.Branch("clasdis_topology",&ev_clasdis_topology,"clasdis_topology/I");
    etree.Branch("has_mc_particle",&ev_has_mc_particle,"has_mc_particle/I");
    etree.Branch("has_mc_recmatch",&ev_has_mc_recmatch,"has_mc_recmatch/I");
    etree.Branch("has_mc_lund",&ev_has_mc_lund,"has_mc_lund/I");
    etree.Branch("gen_n_electron",&ev_gen_n_electron,"gen_n_electron/I");
    etree.Branch("gen_n_positron",&ev_gen_n_positron,"gen_n_positron/I");
    etree.Branch("gen_n_proton",&ev_gen_n_proton,"gen_n_proton/I");
    etree.Branch("gen_n_antiproton",&ev_gen_n_antiproton,"gen_n_antiproton/I");
    etree.Branch("gen_n_neutron",&ev_gen_n_neutron,"gen_n_neutron/I");
    etree.Branch("gen_n_photon",&ev_gen_n_photon,"gen_n_photon/I");
    etree.Branch("gen_n_pi0_photon",&ev_gen_n_pi0_photon,"gen_n_pi0_photon/I");
    etree.Branch("gen_n_piplus",&ev_gen_n_piplus,"gen_n_piplus/I");
    etree.Branch("gen_n_piminus",&ev_gen_n_piminus,"gen_n_piminus/I");
    etree.Branch("gen_n_kplus",&ev_gen_n_kplus,"gen_n_kplus/I");
    etree.Branch("gen_n_kminus",&ev_gen_n_kminus,"gen_n_kminus/I");
    etree.Branch("gen_n_pi0",&ev_gen_n_pi0,"gen_n_pi0/I");
    etree.Branch("gen_n_other",&ev_gen_n_other,"gen_n_other/I");
    etree.Branch("beam_energy",&ev_beam_energy,"beam_energy/D");
    etree.Branch("torus",&ev_torus,"torus/D");
    etree.Branch("solenoid",&ev_solenoid,"solenoid/D");
    etree.Branch("mc_weight",&ev_mc_weight,"mc_weight/D");
    etree.Branch("Q2",&ev_Q2,"Q2/D");
    etree.Branch("W",&ev_W,"W/D");
    etree.Branch("xB",&ev_xB,"xB/D");
    etree.Branch("y",&ev_y,"y/D");
    etree.Branch("e_p",&ev_e_p,"e_p/D");
    etree.Branch("e_theta",&ev_e_theta,"e_theta/D");
    etree.Branch("e_phi",&ev_e_phi,"e_phi/D");
    etree.Branch("e_vx",&ev_e_vx,"e_vx/D");
    etree.Branch("e_vy",&ev_e_vy,"e_vy/D");
    etree.Branch("e_vz",&ev_e_vz,"e_vz/D");
    etree.Branch("rec_rows",&ev_rec_rows,"rec_rows/I");
    etree.Branch("n_neutral",&ev_n_neutral,"n_neutral/I");
    etree.Branch("n_pid22",&ev_n_pid22,"n_pid22/I");
    etree.Branch("n_pid2112",&ev_n_pid2112,"n_pid2112/I");
    etree.Branch("n_pid0_neutral",&ev_n_pid0_neutral,"n_pid0_neutral/I");
    etree.Branch("mc_e_match_count",&ev_mc_e_match_count,"mc_e_match_count/I");
    etree.Branch("mc_e_index",&ev_mc_e_index,"mc_e_index/I");
    etree.Branch("mc_e_pid",&ev_mc_e_pid,"mc_e_pid/I");
    etree.Branch("mc_e_p",&ev_mc_e_p,"mc_e_p/D");
    etree.Branch("mc_e_theta",&ev_mc_e_theta,"mc_e_theta/D");
    etree.Branch("mc_e_phi",&ev_mc_e_phi,"mc_e_phi/D");
    etree.Branch("mc_e_delta_alpha",&ev_mc_e_delta_alpha,"mc_e_delta_alpha/D");
    etree.Branch("rec_pid22_total",&ev_rec_pid22_total,"rec_pid22_total/I");
    etree.Branch("rec_pid22_unmatched",&ev_rec_pid22_unmatched,"rec_pid22_unmatched/I");
    etree.Branch("rec_pid22_multi_mc",&ev_rec_pid22_multi_mc,"rec_pid22_multi_mc/I");
    etree.Branch("rec_pid22_from_mc22",&ev_rec_pid22_from_mc22,"rec_pid22_from_mc22/I");
    etree.Branch("rec_pid22_from_mc11",&ev_rec_pid22_from_mc11,"rec_pid22_from_mc11/I");
    etree.Branch("rec_pid22_from_other",&ev_rec_pid22_from_other,"rec_pid22_from_other/I");
    etree.Branch("ft_pid22_total",&ev_ft_pid22_total,"ft_pid22_total/I");
    etree.Branch("ft_pid22_from_mc22",&ev_ft_pid22_from_mc22,"ft_pid22_from_mc22/I");
    etree.Branch("ft_pid22_from_mc11",&ev_ft_pid22_from_mc11,"ft_pid22_from_mc11/I");
    etree.Branch("ft_pid22_unmatched",&ev_ft_pid22_unmatched,"ft_pid22_unmatched/I");
    etree.Branch("fd_pid22_total",&ev_fd_pid22_total,"fd_pid22_total/I");
    etree.Branch("fd_pid22_from_mc22",&ev_fd_pid22_from_mc22,"fd_pid22_from_mc22/I");
    etree.Branch("fd_pid22_from_mc11",&ev_fd_pid22_from_mc11,"fd_pid22_from_mc11/I");
    etree.Branch("fd_pid22_unmatched",&ev_fd_pid22_unmatched,"fd_pid22_unmatched/I");
    etree.Branch("ft_pid11_total",&ev_ft_pid11_total,"ft_pid11_total/I");
    etree.Branch("ft_pid11_from_mc22",&ev_ft_pid11_from_mc22,"ft_pid11_from_mc22/I");
    etree.Branch("fd_pid11_total",&ev_fd_pid11_total,"fd_pid11_total/I");
    etree.Branch("fd_pid11_from_mc22",&ev_fd_pid11_from_mc22,"fd_pid11_from_mc22/I");
    etree.Branch("fd_pid2112_total",&ev_fd_pid2112_total,"fd_pid2112_total/I");
    etree.Branch("fd_pid2112_from_mc22",&ev_fd_pid2112_from_mc22,"fd_pid2112_from_mc22/I");
    etree.Branch("gen_gamma_total",&ev_gen_gamma_total,"gen_gamma_total/I");
    etree.Branch("gen_gamma_overflow",&ev_gen_gamma_overflow,"gen_gamma_overflow/I");
    etree.Branch("gen_gamma_index",gen_gamma_index,"gen_gamma_index[12]/I");
    etree.Branch("gen_gamma_p",gen_gamma_p,"gen_gamma_p[12]/D");
    etree.Branch("gen_gamma_theta",gen_gamma_theta,"gen_gamma_theta[12]/D");
    etree.Branch("gen_gamma_phi",gen_gamma_phi,"gen_gamma_phi[12]/D");
    etree.Branch("gen_gamma_vx",gen_gamma_vx,"gen_gamma_vx[12]/D");
    etree.Branch("gen_gamma_vy",gen_gamma_vy,"gen_gamma_vy[12]/D");
    etree.Branch("gen_gamma_vz",gen_gamma_vz,"gen_gamma_vz[12]/D");
    etree.Branch("gen_gamma_n_rec_matches",gen_gamma_n_rec_matches,"gen_gamma_n_rec_matches[12]/I");
    etree.Branch("gen_gamma_n_rec_pid22",gen_gamma_n_rec_pid22,"gen_gamma_n_rec_pid22[12]/I");
    etree.Branch("gen_gamma_n_rec_pid11",gen_gamma_n_rec_pid11,"gen_gamma_n_rec_pid11[12]/I");
    etree.Branch("gen_gamma_n_rec_pid2112",gen_gamma_n_rec_pid2112,"gen_gamma_n_rec_pid2112[12]/I");
    etree.Branch("gen_gamma_n_rec_neutral",gen_gamma_n_rec_neutral,"gen_gamma_n_rec_neutral[12]/I");
    etree.Branch("gen_gamma_n_rec_ft",gen_gamma_n_rec_ft,"gen_gamma_n_rec_ft[12]/I");
    etree.Branch("gen_gamma_n_rec_fd",gen_gamma_n_rec_fd,"gen_gamma_n_rec_fd[12]/I");
    etree.Branch("gen_gamma_n_rec_pid22_ft",gen_gamma_n_rec_pid22_ft,"gen_gamma_n_rec_pid22_ft[12]/I");
    etree.Branch("gen_gamma_n_rec_pid22_fd",gen_gamma_n_rec_pid22_fd,"gen_gamma_n_rec_pid22_fd[12]/I");
    etree.Branch("gen_gamma_n_rec_pid11_ft",gen_gamma_n_rec_pid11_ft,"gen_gamma_n_rec_pid11_ft[12]/I");
    etree.Branch("gen_gamma_n_rec_pid11_fd",gen_gamma_n_rec_pid11_fd,"gen_gamma_n_rec_pid11_fd[12]/I");
    etree.Branch("gen_gamma_best_rec_index",gen_gamma_best_rec_index,"gen_gamma_best_rec_index[12]/I");
    etree.Branch("gen_gamma_best_rec_pid",gen_gamma_best_rec_pid,"gen_gamma_best_rec_pid[12]/I");
    etree.Branch("gen_gamma_best_rec_charge",gen_gamma_best_rec_charge,"gen_gamma_best_rec_charge[12]/I");
    etree.Branch("gen_gamma_best_rec_status",gen_gamma_best_rec_status,"gen_gamma_best_rec_status[12]/I");
    etree.Branch("gen_gamma_best_rec_detector",gen_gamma_best_rec_detector,"gen_gamma_best_rec_detector[12]/I");
    etree.Branch("gen_gamma_best_rec_p",gen_gamma_best_rec_p,"gen_gamma_best_rec_p[12]/D");
    etree.Branch("gen_gamma_best_rec_theta",gen_gamma_best_rec_theta,"gen_gamma_best_rec_theta[12]/D");
    etree.Branch("gen_gamma_best_rec_phi",gen_gamma_best_rec_phi,"gen_gamma_best_rec_phi[12]/D");
    etree.Branch("gen_gamma_best_rec_delta_alpha",gen_gamma_best_rec_delta_alpha,"gen_gamma_best_rec_delta_alpha[12]/D");
    etree.Branch("gen_gamma_best_rec_beta",gen_gamma_best_rec_beta,"gen_gamma_best_rec_beta[12]/D");
    etree.Branch("gen_gamma_best_rec_chi2pid",gen_gamma_best_rec_chi2pid,"gen_gamma_best_rec_chi2pid[12]/D");
    etree.Branch("gen_gamma_best_rec_x",gen_gamma_best_rec_x,"gen_gamma_best_rec_x[12]/D");
    etree.Branch("gen_gamma_best_rec_y",gen_gamma_best_rec_y,"gen_gamma_best_rec_y[12]/D");
    etree.Branch("gen_gamma_best_rec_z",gen_gamma_best_rec_z,"gen_gamma_best_rec_z[12]/D");
    etree.Branch("gen_gamma_best_rec_response_energy",gen_gamma_best_rec_response_energy,"gen_gamma_best_rec_response_energy[12]/D");
    etree.Branch("gen_gamma_best_rec_pcal_energy",gen_gamma_best_rec_pcal_energy,"gen_gamma_best_rec_pcal_energy[12]/D");
    etree.Branch("gen_gamma_best_rec_ecin_energy",gen_gamma_best_rec_ecin_energy,"gen_gamma_best_rec_ecin_energy[12]/D");
    etree.Branch("gen_gamma_best_rec_ecout_energy",gen_gamma_best_rec_ecout_energy,"gen_gamma_best_rec_ecout_energy[12]/D");
    etree.Branch("gen_gamma_best_rec_ecal_energy",gen_gamma_best_rec_ecal_energy,"gen_gamma_best_rec_ecal_energy[12]/D");
    etree.Branch("gen_gamma_best_rec_ft_energy",gen_gamma_best_rec_ft_energy,"gen_gamma_best_rec_ft_energy[12]/D");
    etree.Branch("gen_gamma_best_rec_ft_radius",gen_gamma_best_rec_ft_radius,"gen_gamma_best_rec_ft_radius[12]/D");
    string eline;
    while(getline(ein,eline)){
      if(eline.empty() || eline[0]=='#') continue;
      istringstream ss(eline); bool ok=true;
#define ERD(x) do{ if(!(ss>>(x))) ok=false; }while(0)
      ERD(ev_skim_version);
      ERD(ev_source_file_hash);
      ERD(ev_runnum);
      ERD(ev_evnum);
      ERD(ev_helicity);
      ERD(ev_is_mc);
      ERD(ev_sample_kind);
      ERD(ev_clasdis_topology);
      ERD(ev_has_mc_particle);
      ERD(ev_has_mc_recmatch);
      ERD(ev_has_mc_lund);
      ERD(ev_gen_n_electron);
      ERD(ev_gen_n_positron);
      ERD(ev_gen_n_proton);
      ERD(ev_gen_n_antiproton);
      ERD(ev_gen_n_neutron);
      ERD(ev_gen_n_photon);
      ERD(ev_gen_n_pi0_photon);
      ERD(ev_gen_n_piplus);
      ERD(ev_gen_n_piminus);
      ERD(ev_gen_n_kplus);
      ERD(ev_gen_n_kminus);
      ERD(ev_gen_n_pi0);
      ERD(ev_gen_n_other);
      ERD(ev_beam_energy);
      ERD(ev_torus);
      ERD(ev_solenoid);
      ERD(ev_mc_weight);
      ERD(ev_Q2);
      ERD(ev_W);
      ERD(ev_xB);
      ERD(ev_y);
      ERD(ev_e_p);
      ERD(ev_e_theta);
      ERD(ev_e_phi);
      ERD(ev_e_vx);
      ERD(ev_e_vy);
      ERD(ev_e_vz);
      ERD(ev_rec_rows);
      ERD(ev_n_neutral);
      ERD(ev_n_pid22);
      ERD(ev_n_pid2112);
      ERD(ev_n_pid0_neutral);
      ERD(ev_mc_e_match_count);
      ERD(ev_mc_e_index);
      ERD(ev_mc_e_pid);
      ERD(ev_mc_e_p);
      ERD(ev_mc_e_theta);
      ERD(ev_mc_e_phi);
      ERD(ev_mc_e_delta_alpha);
      ERD(ev_rec_pid22_total);
      ERD(ev_rec_pid22_unmatched);
      ERD(ev_rec_pid22_multi_mc);
      ERD(ev_rec_pid22_from_mc22);
      ERD(ev_rec_pid22_from_mc11);
      ERD(ev_rec_pid22_from_other);
      ERD(ev_ft_pid22_total);
      ERD(ev_ft_pid22_from_mc22);
      ERD(ev_ft_pid22_from_mc11);
      ERD(ev_ft_pid22_unmatched);
      ERD(ev_fd_pid22_total);
      ERD(ev_fd_pid22_from_mc22);
      ERD(ev_fd_pid22_from_mc11);
      ERD(ev_fd_pid22_unmatched);
      ERD(ev_ft_pid11_total);
      ERD(ev_ft_pid11_from_mc22);
      ERD(ev_fd_pid11_total);
      ERD(ev_fd_pid11_from_mc22);
      ERD(ev_fd_pid2112_total);
      ERD(ev_fd_pid2112_from_mc22);
      ERD(ev_gen_gamma_total);
      ERD(ev_gen_gamma_overflow);
      // The .events intermediate is sparse: only min(gen_gamma_total,12)
      // generated-photon records are written.  Initialize the fixed ROOT arrays
      // here so the ROOT schema remains exactly 12 slots without forcing the
      // Groovy producer to write hundreds of useless -999 tokens per event.
      for(int k=0;k<NGEN;k++){
        gen_gamma_index[k]=-999; gen_gamma_p[k]=-999.; gen_gamma_theta[k]=-999.; gen_gamma_phi[k]=-999.;
        gen_gamma_vx[k]=-999.; gen_gamma_vy[k]=-999.; gen_gamma_vz[k]=-999.;
        gen_gamma_n_rec_matches[k]=-999; gen_gamma_n_rec_pid22[k]=-999; gen_gamma_n_rec_pid11[k]=-999; gen_gamma_n_rec_pid2112[k]=-999;
        gen_gamma_n_rec_neutral[k]=-999; gen_gamma_n_rec_ft[k]=-999; gen_gamma_n_rec_fd[k]=-999;
        gen_gamma_n_rec_pid22_ft[k]=-999; gen_gamma_n_rec_pid22_fd[k]=-999; gen_gamma_n_rec_pid11_ft[k]=-999; gen_gamma_n_rec_pid11_fd[k]=-999;
        gen_gamma_best_rec_index[k]=-999; gen_gamma_best_rec_pid[k]=-999; gen_gamma_best_rec_charge[k]=-999; gen_gamma_best_rec_status[k]=-999; gen_gamma_best_rec_detector[k]=-999;
        gen_gamma_best_rec_p[k]=-999.; gen_gamma_best_rec_theta[k]=-999.; gen_gamma_best_rec_phi[k]=-999.; gen_gamma_best_rec_delta_alpha[k]=-999.;
        gen_gamma_best_rec_beta[k]=-999.; gen_gamma_best_rec_chi2pid[k]=-999.; gen_gamma_best_rec_x[k]=-999.; gen_gamma_best_rec_y[k]=-999.; gen_gamma_best_rec_z[k]=-999.;
        gen_gamma_best_rec_response_energy[k]=-999.; gen_gamma_best_rec_pcal_energy[k]=-999.; gen_gamma_best_rec_ecin_energy[k]=-999.;
        gen_gamma_best_rec_ecout_energy[k]=-999.; gen_gamma_best_rec_ecal_energy[k]=-999.; gen_gamma_best_rec_ft_energy[k]=-999.; gen_gamma_best_rec_ft_radius[k]=-999.;
      }
      const int nStoredGamma = std::max(0,std::min(NGEN,ev_gen_gamma_total));
      for(int k=0;k<nStoredGamma;k++){
        ERD(gen_gamma_index[k]);
        ERD(gen_gamma_p[k]);
        ERD(gen_gamma_theta[k]);
        ERD(gen_gamma_phi[k]);
        ERD(gen_gamma_vx[k]);
        ERD(gen_gamma_vy[k]);
        ERD(gen_gamma_vz[k]);
        ERD(gen_gamma_n_rec_matches[k]);
        ERD(gen_gamma_n_rec_pid22[k]);
        ERD(gen_gamma_n_rec_pid11[k]);
        ERD(gen_gamma_n_rec_pid2112[k]);
        ERD(gen_gamma_n_rec_neutral[k]);
        ERD(gen_gamma_n_rec_ft[k]);
        ERD(gen_gamma_n_rec_fd[k]);
        ERD(gen_gamma_n_rec_pid22_ft[k]);
        ERD(gen_gamma_n_rec_pid22_fd[k]);
        ERD(gen_gamma_n_rec_pid11_ft[k]);
        ERD(gen_gamma_n_rec_pid11_fd[k]);
        ERD(gen_gamma_best_rec_index[k]);
        ERD(gen_gamma_best_rec_pid[k]);
        ERD(gen_gamma_best_rec_charge[k]);
        ERD(gen_gamma_best_rec_status[k]);
        ERD(gen_gamma_best_rec_detector[k]);
        ERD(gen_gamma_best_rec_p[k]);
        ERD(gen_gamma_best_rec_theta[k]);
        ERD(gen_gamma_best_rec_phi[k]);
        ERD(gen_gamma_best_rec_delta_alpha[k]);
        ERD(gen_gamma_best_rec_beta[k]);
        ERD(gen_gamma_best_rec_chi2pid[k]);
        ERD(gen_gamma_best_rec_x[k]);
        ERD(gen_gamma_best_rec_y[k]);
        ERD(gen_gamma_best_rec_z[k]);
        ERD(gen_gamma_best_rec_response_energy[k]);
        ERD(gen_gamma_best_rec_pcal_energy[k]);
        ERD(gen_gamma_best_rec_ecin_energy[k]);
        ERD(gen_gamma_best_rec_ecout_energy[k]);
        ERD(gen_gamma_best_rec_ecal_energy[k]);
        ERD(gen_gamma_best_rec_ft_energy[k]);
        ERD(gen_gamma_best_rec_ft_radius[k]);
      }
#undef ERD
      if(!ok){ ebad++; continue; }
      etree.Fill(); en++;
    }
    etree.Write();
  } else {
    cerr<<"WARNING: companion event file not found: "<<eventPath<<"\n";
  }
  out.Close();
  cout<<"Wrote "<<n<<" PhotonEfficiency entries"; if(bad) cout<<" (skipped "<<bad<<" malformed hypothesis lines)"; cout<<"\n";
  if(en || ebad) { cout<<"Wrote "<<en<<" PhotonEfficiencyEvents entries"; if(ebad) cout<<" (skipped "<<ebad<<" malformed event lines)"; cout<<"\n"; }
  return (bad||ebad)?3:0;
}
