#include <TFile.h>
#include <TTree.h>
#include <fstream>
#include <iostream>
#include <sstream>
#include <string>
using namespace std;

int main(int argc,char** argv){
  if(argc!=3){ cerr<<"Usage: "<<argv[0]<<" input.txt output.root\n"; return 1; }
  ifstream in(argv[1]); if(!in){ cerr<<"Cannot open "<<argv[1]<<"\n"; return 2; }
  TFile out(argv[2],"RECREATE");
  TTree tree("PhotonEfficiency","Photon efficiency tag-and-probe hypotheses");
  int runnum;
  int evnum;
  int helicity;
  int is_mc;
  double beam_energy;
  double torus;
  double solenoid;
  double mc_weight;
  int rec_rows;
  int n_neutral;
  int n_pid22;
  int n_pid2112;
  int n_pid0_neutral;
  double Q2;
  double W;
  double xB;
  double y;
  double minus_t;
  double e_p;
  double e_theta;
  double e_phi;
  double e_vx;
  double e_vy;
  double e_vz;
  int p_rec_index;
  int p_detector;
  int p_pass_standard;
  double p_raw_p;
  double p_raw_theta;
  double p_raw_phi;
  double p_corr_p;
  double p_corr_theta;
  double p_corr_phi;
  double p_vz;
  int tag_rec_index;
  int tag_detector;
  int tag_status;
  int tag_pass_beta;
  int tag_pass_fiducial;
  double tag_raw_p;
  double tag_raw_theta;
  double tag_raw_phi;
  double tag_beta;
  double tag_corr_p;
  double tag_corr_theta;
  double tag_corr_phi;
  double tag_x;
  double tag_y;
  double tag_z;
  double tag_r;
  double Mx2_ep;
  double Mx_ep;
  double Mx2_epg_raw;
  double probe_raw_E;
  double probe_raw_p;
  double probe_raw_theta;
  double probe_raw_phi;
  double probe_raw_px;
  double probe_raw_py;
  double probe_raw_pz;
  double Mx2_epg_corr;
  double probe_corr_E;
  double probe_corr_p;
  double probe_corr_theta;
  double probe_corr_phi;
  double probe_corr_px;
  double probe_corr_py;
  double probe_corr_pz;
  int truth_probe_index;
  int truth_probe_pid;
  int truth_probe_parent;
  double truth_probe_p;
  double truth_probe_theta;
  double truth_probe_phi;
  double truth_probe_delta_alpha;
  int truth_tag_index;
  int truth_tag_pid;
  int truth_tag_parent;
  double truth_tag_p;
  double truth_tag_theta;
  double truth_tag_phi;
  double truth_tag_delta_alpha;
  const int NNEU=5, NANY=3;
  int neutral_idx[5],neutral_pid[5],neutral_charge[5],neutral_status[5],neutral_detector[5];
  double neutral_p[5],neutral_theta[5],neutral_phi[5],neutral_delta_alpha[5],neutral_x[5],neutral_y[5],neutral_z[5];
  int any_idx[3],any_pid[3],any_charge[3],any_status[3],any_detector[3];
  double any_p[3],any_theta[3],any_phi[3],any_delta_alpha[3],any_x[3],any_y[3],any_z[3];
  tree.Branch("runnum",&runnum,"runnum/I");
  tree.Branch("evnum",&evnum,"evnum/I");
  tree.Branch("helicity",&helicity,"helicity/I");
  tree.Branch("is_mc",&is_mc,"is_mc/I");
  tree.Branch("beam_energy",&beam_energy,"beam_energy/D");
  tree.Branch("torus",&torus,"torus/D");
  tree.Branch("solenoid",&solenoid,"solenoid/D");
  tree.Branch("mc_weight",&mc_weight,"mc_weight/D");
  tree.Branch("rec_rows",&rec_rows,"rec_rows/I");
  tree.Branch("n_neutral",&n_neutral,"n_neutral/I");
  tree.Branch("n_pid22",&n_pid22,"n_pid22/I");
  tree.Branch("n_pid2112",&n_pid2112,"n_pid2112/I");
  tree.Branch("n_pid0_neutral",&n_pid0_neutral,"n_pid0_neutral/I");
  tree.Branch("Q2",&Q2,"Q2/D");
  tree.Branch("W",&W,"W/D");
  tree.Branch("xB",&xB,"xB/D");
  tree.Branch("y",&y,"y/D");
  tree.Branch("minus_t",&minus_t,"minus_t/D");
  tree.Branch("e_p",&e_p,"e_p/D");
  tree.Branch("e_theta",&e_theta,"e_theta/D");
  tree.Branch("e_phi",&e_phi,"e_phi/D");
  tree.Branch("e_vx",&e_vx,"e_vx/D");
  tree.Branch("e_vy",&e_vy,"e_vy/D");
  tree.Branch("e_vz",&e_vz,"e_vz/D");
  tree.Branch("p_rec_index",&p_rec_index,"p_rec_index/I");
  tree.Branch("p_detector",&p_detector,"p_detector/I");
  tree.Branch("p_pass_standard",&p_pass_standard,"p_pass_standard/I");
  tree.Branch("p_raw_p",&p_raw_p,"p_raw_p/D");
  tree.Branch("p_raw_theta",&p_raw_theta,"p_raw_theta/D");
  tree.Branch("p_raw_phi",&p_raw_phi,"p_raw_phi/D");
  tree.Branch("p_corr_p",&p_corr_p,"p_corr_p/D");
  tree.Branch("p_corr_theta",&p_corr_theta,"p_corr_theta/D");
  tree.Branch("p_corr_phi",&p_corr_phi,"p_corr_phi/D");
  tree.Branch("p_vz",&p_vz,"p_vz/D");
  tree.Branch("tag_rec_index",&tag_rec_index,"tag_rec_index/I");
  tree.Branch("tag_detector",&tag_detector,"tag_detector/I");
  tree.Branch("tag_status",&tag_status,"tag_status/I");
  tree.Branch("tag_pass_beta",&tag_pass_beta,"tag_pass_beta/I");
  tree.Branch("tag_pass_fiducial",&tag_pass_fiducial,"tag_pass_fiducial/I");
  tree.Branch("tag_raw_p",&tag_raw_p,"tag_raw_p/D");
  tree.Branch("tag_raw_theta",&tag_raw_theta,"tag_raw_theta/D");
  tree.Branch("tag_raw_phi",&tag_raw_phi,"tag_raw_phi/D");
  tree.Branch("tag_beta",&tag_beta,"tag_beta/D");
  tree.Branch("tag_corr_p",&tag_corr_p,"tag_corr_p/D");
  tree.Branch("tag_corr_theta",&tag_corr_theta,"tag_corr_theta/D");
  tree.Branch("tag_corr_phi",&tag_corr_phi,"tag_corr_phi/D");
  tree.Branch("tag_x",&tag_x,"tag_x/D");
  tree.Branch("tag_y",&tag_y,"tag_y/D");
  tree.Branch("tag_z",&tag_z,"tag_z/D");
  tree.Branch("tag_r",&tag_r,"tag_r/D");
  tree.Branch("Mx2_ep",&Mx2_ep,"Mx2_ep/D");
  tree.Branch("Mx_ep",&Mx_ep,"Mx_ep/D");
  tree.Branch("Mx2_epg_raw",&Mx2_epg_raw,"Mx2_epg_raw/D");
  tree.Branch("probe_raw_E",&probe_raw_E,"probe_raw_E/D");
  tree.Branch("probe_raw_p",&probe_raw_p,"probe_raw_p/D");
  tree.Branch("probe_raw_theta",&probe_raw_theta,"probe_raw_theta/D");
  tree.Branch("probe_raw_phi",&probe_raw_phi,"probe_raw_phi/D");
  tree.Branch("probe_raw_px",&probe_raw_px,"probe_raw_px/D");
  tree.Branch("probe_raw_py",&probe_raw_py,"probe_raw_py/D");
  tree.Branch("probe_raw_pz",&probe_raw_pz,"probe_raw_pz/D");
  tree.Branch("Mx2_epg_corr",&Mx2_epg_corr,"Mx2_epg_corr/D");
  tree.Branch("probe_corr_E",&probe_corr_E,"probe_corr_E/D");
  tree.Branch("probe_corr_p",&probe_corr_p,"probe_corr_p/D");
  tree.Branch("probe_corr_theta",&probe_corr_theta,"probe_corr_theta/D");
  tree.Branch("probe_corr_phi",&probe_corr_phi,"probe_corr_phi/D");
  tree.Branch("probe_corr_px",&probe_corr_px,"probe_corr_px/D");
  tree.Branch("probe_corr_py",&probe_corr_py,"probe_corr_py/D");
  tree.Branch("probe_corr_pz",&probe_corr_pz,"probe_corr_pz/D");
  tree.Branch("truth_probe_index",&truth_probe_index,"truth_probe_index/I");
  tree.Branch("truth_probe_pid",&truth_probe_pid,"truth_probe_pid/I");
  tree.Branch("truth_probe_parent",&truth_probe_parent,"truth_probe_parent/I");
  tree.Branch("truth_probe_p",&truth_probe_p,"truth_probe_p/D");
  tree.Branch("truth_probe_theta",&truth_probe_theta,"truth_probe_theta/D");
  tree.Branch("truth_probe_phi",&truth_probe_phi,"truth_probe_phi/D");
  tree.Branch("truth_probe_delta_alpha",&truth_probe_delta_alpha,"truth_probe_delta_alpha/D");
  tree.Branch("truth_tag_index",&truth_tag_index,"truth_tag_index/I");
  tree.Branch("truth_tag_pid",&truth_tag_pid,"truth_tag_pid/I");
  tree.Branch("truth_tag_parent",&truth_tag_parent,"truth_tag_parent/I");
  tree.Branch("truth_tag_p",&truth_tag_p,"truth_tag_p/D");
  tree.Branch("truth_tag_theta",&truth_tag_theta,"truth_tag_theta/D");
  tree.Branch("truth_tag_phi",&truth_tag_phi,"truth_tag_phi/D");
  tree.Branch("truth_tag_delta_alpha",&truth_tag_delta_alpha,"truth_tag_delta_alpha/D");
  tree.Branch("neutral_idx",neutral_idx,"neutral_idx[5]/I");
  tree.Branch("neutral_pid",neutral_pid,"neutral_pid[5]/I");
  tree.Branch("neutral_charge",neutral_charge,"neutral_charge[5]/I");
  tree.Branch("neutral_status",neutral_status,"neutral_status[5]/I");
  tree.Branch("neutral_detector",neutral_detector,"neutral_detector[5]/I");
  tree.Branch("neutral_p",neutral_p,"neutral_p[5]/D");
  tree.Branch("neutral_theta",neutral_theta,"neutral_theta[5]/D");
  tree.Branch("neutral_phi",neutral_phi,"neutral_phi[5]/D");
  tree.Branch("neutral_delta_alpha",neutral_delta_alpha,"neutral_delta_alpha[5]/D");
  tree.Branch("neutral_x",neutral_x,"neutral_x[5]/D");
  tree.Branch("neutral_y",neutral_y,"neutral_y[5]/D");
  tree.Branch("neutral_z",neutral_z,"neutral_z[5]/D");
  tree.Branch("any_idx",any_idx,"any_idx[3]/I");
  tree.Branch("any_pid",any_pid,"any_pid[3]/I");
  tree.Branch("any_charge",any_charge,"any_charge[3]/I");
  tree.Branch("any_status",any_status,"any_status[3]/I");
  tree.Branch("any_detector",any_detector,"any_detector[3]/I");
  tree.Branch("any_p",any_p,"any_p[3]/D");
  tree.Branch("any_theta",any_theta,"any_theta[3]/D");
  tree.Branch("any_phi",any_phi,"any_phi[3]/D");
  tree.Branch("any_delta_alpha",any_delta_alpha,"any_delta_alpha[3]/D");
  tree.Branch("any_x",any_x,"any_x[3]/D");
  tree.Branch("any_y",any_y,"any_y[3]/D");
  tree.Branch("any_z",any_z,"any_z[3]/D");
  string line; long long n=0,bad=0;
  while(getline(in,line)){
    if(line.empty() || line[0]=='#') continue;
    istringstream ss(line);
    bool ok=true;
    if(!(ss>>runnum)) ok=false;
    if(!(ss>>evnum)) ok=false;
    if(!(ss>>helicity)) ok=false;
    if(!(ss>>is_mc)) ok=false;
    if(!(ss>>beam_energy)) ok=false;
    if(!(ss>>torus)) ok=false;
    if(!(ss>>solenoid)) ok=false;
    if(!(ss>>mc_weight)) ok=false;
    if(!(ss>>rec_rows)) ok=false;
    if(!(ss>>n_neutral)) ok=false;
    if(!(ss>>n_pid22)) ok=false;
    if(!(ss>>n_pid2112)) ok=false;
    if(!(ss>>n_pid0_neutral)) ok=false;
    if(!(ss>>Q2)) ok=false;
    if(!(ss>>W)) ok=false;
    if(!(ss>>xB)) ok=false;
    if(!(ss>>y)) ok=false;
    if(!(ss>>minus_t)) ok=false;
    if(!(ss>>e_p)) ok=false;
    if(!(ss>>e_theta)) ok=false;
    if(!(ss>>e_phi)) ok=false;
    if(!(ss>>e_vx)) ok=false;
    if(!(ss>>e_vy)) ok=false;
    if(!(ss>>e_vz)) ok=false;
    if(!(ss>>p_rec_index)) ok=false;
    if(!(ss>>p_detector)) ok=false;
    if(!(ss>>p_pass_standard)) ok=false;
    if(!(ss>>p_raw_p)) ok=false;
    if(!(ss>>p_raw_theta)) ok=false;
    if(!(ss>>p_raw_phi)) ok=false;
    if(!(ss>>p_corr_p)) ok=false;
    if(!(ss>>p_corr_theta)) ok=false;
    if(!(ss>>p_corr_phi)) ok=false;
    if(!(ss>>p_vz)) ok=false;
    if(!(ss>>tag_rec_index)) ok=false;
    if(!(ss>>tag_detector)) ok=false;
    if(!(ss>>tag_status)) ok=false;
    if(!(ss>>tag_pass_beta)) ok=false;
    if(!(ss>>tag_pass_fiducial)) ok=false;
    if(!(ss>>tag_raw_p)) ok=false;
    if(!(ss>>tag_raw_theta)) ok=false;
    if(!(ss>>tag_raw_phi)) ok=false;
    if(!(ss>>tag_beta)) ok=false;
    if(!(ss>>tag_corr_p)) ok=false;
    if(!(ss>>tag_corr_theta)) ok=false;
    if(!(ss>>tag_corr_phi)) ok=false;
    if(!(ss>>tag_x)) ok=false;
    if(!(ss>>tag_y)) ok=false;
    if(!(ss>>tag_z)) ok=false;
    if(!(ss>>tag_r)) ok=false;
    if(!(ss>>Mx2_ep)) ok=false;
    if(!(ss>>Mx_ep)) ok=false;
    if(!(ss>>Mx2_epg_raw)) ok=false;
    if(!(ss>>probe_raw_E)) ok=false;
    if(!(ss>>probe_raw_p)) ok=false;
    if(!(ss>>probe_raw_theta)) ok=false;
    if(!(ss>>probe_raw_phi)) ok=false;
    if(!(ss>>probe_raw_px)) ok=false;
    if(!(ss>>probe_raw_py)) ok=false;
    if(!(ss>>probe_raw_pz)) ok=false;
    if(!(ss>>Mx2_epg_corr)) ok=false;
    if(!(ss>>probe_corr_E)) ok=false;
    if(!(ss>>probe_corr_p)) ok=false;
    if(!(ss>>probe_corr_theta)) ok=false;
    if(!(ss>>probe_corr_phi)) ok=false;
    if(!(ss>>probe_corr_px)) ok=false;
    if(!(ss>>probe_corr_py)) ok=false;
    if(!(ss>>probe_corr_pz)) ok=false;
    for(int k=0;k<NNEU;k++){ if(!(ss>>neutral_idx[k]>>neutral_pid[k]>>neutral_charge[k]>>neutral_status[k]>>neutral_detector[k]>>neutral_p[k]>>neutral_theta[k]>>neutral_phi[k]>>neutral_delta_alpha[k]>>neutral_x[k]>>neutral_y[k]>>neutral_z[k])) ok=false; }
    for(int k=0;k<NANY;k++){ if(!(ss>>any_idx[k]>>any_pid[k]>>any_charge[k]>>any_status[k]>>any_detector[k]>>any_p[k]>>any_theta[k]>>any_phi[k]>>any_delta_alpha[k]>>any_x[k]>>any_y[k]>>any_z[k])) ok=false; }
    if(!(ss>>truth_probe_index)) ok=false;
    if(!(ss>>truth_probe_pid)) ok=false;
    if(!(ss>>truth_probe_parent)) ok=false;
    if(!(ss>>truth_probe_p)) ok=false;
    if(!(ss>>truth_probe_theta)) ok=false;
    if(!(ss>>truth_probe_phi)) ok=false;
    if(!(ss>>truth_probe_delta_alpha)) ok=false;
    if(!(ss>>truth_tag_index)) ok=false;
    if(!(ss>>truth_tag_pid)) ok=false;
    if(!(ss>>truth_tag_parent)) ok=false;
    if(!(ss>>truth_tag_p)) ok=false;
    if(!(ss>>truth_tag_theta)) ok=false;
    if(!(ss>>truth_tag_phi)) ok=false;
    if(!(ss>>truth_tag_delta_alpha)) ok=false;
    if(!ok){ bad++; continue; }
    tree.Fill(); n++;
  }
  tree.Write(); out.Close();
  cout<<"Wrote "<<n<<" entries to "<<argv[2]; if(bad) cout<<" (skipped "<<bad<<" malformed lines)"; cout<<"\n";
  return bad?3:0;
}
